language: node_js
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+$/"  # Use sem var
# GOTCHA: Letting Travis handle `install` and `script` with default values
deploy:
  provider: heroku
  api_key:
    secure: UIGb9dnK3ftyA9cXHZzx0WSFcolHfZSUGWNqXx/bHpGoq/R2i8QZn4FXvwH9uP0dKPdzFOAsT57Zg09iHNVg7Ac+iIVtgC9uDRFKV0+pVvBSmBlNP5yEIcEMvje2jzSdjSTqrY40NXRl9OLkPmv6AtoV3PDFdwB4lR0YX/OdtJZQWDpa0uA6nZxEc4R4mifA6DYSDkC2CJuFE7xmZDc7sYWD4/ZU7xEE6f6K2645GvbEK68AbA6baMwWRPeLOEOFk4rLBA+LV8F1ObSmpAWu3SjiQkkxsckdD9ZOpLe7M5AENqhcZ8IXfumjKbCzXUvLbpvEOMCF9k5nVb0/EfZb4++Px5Ec5XQ0NHbloaDebYWDUhpC9YWa7nVbucs1GAjl+oe99bLjXKYGl75yKI9iW+a6PkAEwxoGFfQf+/qEVAkOw03s4uTYvCcOWRAXGyiBRfbyu+0gLX2ClobY45jvGU1xtda4AKwuOuUECsObKR+1wpKpf0D7yudL7vgvOHzUrys5hlo9Woff5ZMOMYhAKdO+gMAP4Scaov24D93U98/lJztIzxGCr9bwgvs6rd9AfkdD9MPQmfnR0fDemFTqs2qfEiB/IHxzgGTlyQtB7Cmvh1I0p8v4V5cwatI1ZUgjnt0lVrDGY8Q/dd+AEmnDHCP0uZhSpd4mZ9Q9AeWrB0A=
  app: phan-pil-bot
  on:
    tags: true
    repo: hanpeter/pil-bot
