language: node_js
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+$/"  # Use sem var
# GOTCHA: Letting Travis handle `install` and `script` with default values
deploy:
  provider: heroku
  api_key:
    secure: JS5mKejMdV4SEF92YZblQ3IP5JKDDKPTk3TZyXuO80+gNF1K71HwiBds6f/tLAIdPgNTt0oH2qx58p806K4Se35/giWM032tShOkINmdpoTbc2NO11+Vh/UwUB+kdpeMCm9egC1opanpkcFEGl0nu1dO9s1w0XJHKC6LD8xbRCLjHYHPGEMcWCuHjR8vyC2qizVPPJ/SrOsUd+YUdhHdJ32OETf5BsIJ0cV1/Fs5IhxKhVAzEznnZAm/8pChJTt0WkI5eEIMNm+yk5mTU0P4jJpIkIHZKTX6p2EMX/wxugkf0SOWlFx0NWY0xF6Ak2LEnZi6mpJDUSMCeaNYeBuWqYGzD7s5YL82163B1BA6R4+jpDBJTOQsyzAvoZPiMDCRupwOCODVQDRttNnTfvc7tYShi0jrcmMPEXB4EVfDg9IFn5Ojb6QiLBv9xpmDBamVXML9KhG3xX48puLYldUqra5walM5bwQ59eHP/yHBTyChBCeV3OzWMlOqCBtZ24FfAQ2U4JJMUQT1pGbCVfFl0prUe9TM6vTtY/qnYW/w8yTIDYsxGYqS0qTbugJSgidHliJFOofdr5ARGrjmCzyO/hUx+8/kubyPTuWQoAq6Py4y4b1qgNjhX+I+6NjDv2w4U3HTPlAPUEGus83KLHRU6V/iZ3MnlmnqKYhlja3PhIs=
  app: phan-pil-bot
  on:
    tags: true
    repo: hanpeter/pil-bot
